use crate::code_audit::conventions::Language;
use crate::code_audit::{AuditFinding, CodeAuditResult};
use crate::core::refactor::auto::{Fix, FixSafetyTier, InsertionKind, NewFile, SkippedFile};
use crate::core::refactor::shared::detect_language;
use std::path::Path;

use super::{insertion, new_file};

pub(crate) fn extract_expected_test_path(description: &str) -> Option<String> {
    let needle = "expected '";
    let start = description.find(needle)? + needle.len();
    let rest = &description[start..];
    let end = rest.find('\'')?;
    Some(rest[..end].to_string())
}

pub(crate) fn extract_expected_test_method(description: &str) -> Option<String> {
    let needle = "expected '";
    let start = description.find(needle)? + needle.len();
    let rest = &description[start..];
    let end = rest.find('\'')?;
    Some(rest[..end].to_string())
}

pub(crate) fn extract_test_file_from_missing_test_method(description: &str) -> Option<String> {
    let needle = " in '";
    let start = description.find(needle)? + needle.len();
    let rest = &description[start..];
    let end = rest.find('\'')?;
    Some(rest[..end].to_string())
}

pub(crate) fn extract_source_method_name(description: &str) -> Option<String> {
    let needle = "Method '";
    let start = description.find(needle)? + needle.len();
    let rest = &description[start..];
    let end = rest.find('\'')?;
    Some(rest[..end].to_string())
}

pub(crate) fn generate_test_method_stub(
    language: &Language,
    expected_test_method: &str,
    source_file: &str,
    source_method: &str,
) -> String {
    match language {
        Language::Rust => format!(
            "#[test]\n#[ignore = \"autogenerated scaffold\"]\nfn {}() {{\n    todo!(\"Autogenerated scaffold for {}::{}\");\n}}\n",
            expected_test_method, source_file, source_method
        ),
        Language::Php => format!(
            "public function {}(): void {{\n    $this->markTestIncomplete('Autogenerated scaffold for {}::{}');\n}}\n",
            expected_test_method, source_file, source_method
        ),
        _ => format!(
            "// Add {} for {}::{}\n",
            expected_test_method, source_file, source_method
        ),
    }
}

pub(crate) fn is_inline_test_language(language: &Language) -> bool {
    matches!(language, Language::Rust)
}

pub(crate) fn generate_test_file_stub(test_file: &str, source_file: &str) -> String {
    let ext = Path::new(test_file)
        .extension()
        .and_then(|ext| ext.to_str())
        .map(Language::from_extension)
        .unwrap_or(Language::Unknown);

    match ext {
        Language::Rust => {
            let name = Path::new(source_file)
                .file_stem()
                .and_then(|stem| stem.to_str())
                .unwrap_or("module")
                .replace('-', "_");
            format!(
                "// Auto-generated by `homeboy audit --fix`\n// Source: {}\n\n#[test]\n#[ignore = \"autogenerated scaffold\"]\nfn test_{}_placeholder() {{\n    todo!(\"Autogenerated scaffold - replace with real assertions\");\n}}\n",
                source_file, name
            )
        }
        Language::Php => {
            format!(
                "<?php\n\n// Auto-generated by `homeboy audit --fix`\n// Source: {}\n\nuse PHPUnit\\Framework\\TestCase;\n\nfinal class GeneratedPlaceholderTest extends TestCase {{\n    public function test_placeholder(): void {{\n        $this->markTestIncomplete('Autogenerated scaffold - replace with real assertions');\n    }}\n}}\n",
                source_file
            )
        }
        _ => format!(
            "// Auto-generated by `homeboy audit --fix`\n// Source: {}\n// Add tests\n",
            source_file
        ),
    }
}

pub(crate) struct TestFileCandidate {
    pub content: String,
}

pub(crate) fn generate_test_file_candidate(
    root: &Path,
    test_file: &str,
    source_file: &str,
) -> Option<TestFileCandidate> {
    if let Some(scaffolded) = generate_test_file_from_scaffold(root, test_file, source_file) {
        return Some(TestFileCandidate {
            content: scaffolded,
        });
    }

    Some(TestFileCandidate {
        content: generate_test_file_stub(test_file, source_file),
    })
}

fn extract_source_file_from_comment(content: &str) -> Option<String> {
    content.lines().find_map(|line| {
        line.trim()
            .strip_prefix("// Source: ")
            .or_else(|| line.trim().strip_prefix("* Source: "))
            .or_else(|| line.trim().strip_prefix("// Source: "))
            .map(|value| value.trim().to_string())
    })
}

pub(crate) fn mapping_from_source_comment(content: &str) -> Option<(String, String)> {
    let source_file = extract_source_file_from_comment(content)?;
    let expected_test_path = derive_expected_test_file_path(Path::new("."), &source_file)
        .or_else(|| fallback_expected_test_path(&source_file))?;

    Some((source_file, expected_test_path))
}

fn fallback_expected_test_path(source_file: &str) -> Option<String> {
    let source_path = Path::new(source_file);
    let ext = source_path.extension()?.to_str()?;
    let name = source_path.file_stem()?.to_str()?;
    let dir = source_path
        .parent()
        .and_then(|parent| parent.strip_prefix("src").ok())
        .map(|parent| parent.to_string_lossy().trim_start_matches('/').to_string())
        .unwrap_or_default();

    Some(if dir.is_empty() {
        format!("tests/{}_test.{}", name, ext)
    } else {
        format!("tests/{}/{}_test.{}", dir, name, ext)
    })
}

pub(crate) fn extract_source_file_from_test_stub(description: &str) -> Option<String> {
    let marker = " for '";
    let start = description.find(marker)? + marker.len();
    let rest = &description[start..];
    let end = rest.find("::")?;
    Some(rest[..end].to_string())
}

pub(crate) fn extract_expected_test_method_from_fix_description(
    description: &str,
) -> Option<String> {
    let marker = "Scaffold missing test method '";
    let start = description.find(marker)? + marker.len();
    let rest = &description[start..];
    let end = rest.find('"').or_else(|| rest.find('\''))?;
    Some(rest[..end].to_string())
}

pub(crate) fn test_method_exists_in_file(
    root: &Path,
    test_file: &str,
    expected_test_method: &str,
    new_files: &[NewFile],
) -> bool {
    if let Some(new_file) = new_files.iter().find(|new_file| new_file.file == test_file) {
        return new_file.content.contains(expected_test_method);
    }

    let abs_path = root.join(test_file);
    match std::fs::read_to_string(&abs_path) {
        Ok(content) => content.contains(expected_test_method),
        Err(_) => false,
    }
}

pub(crate) fn derive_expected_test_file_path(root: &Path, source_file: &str) -> Option<String> {
    let ext = Path::new(source_file).extension()?.to_str()?;
    let manifest = crate::extension::find_extension_for_file_ext(ext, "audit")?;
    let mapping = manifest.test_mapping()?;

    let mut path = crate::code_audit::test_mapping::source_to_test_path(source_file, mapping)?;
    if path.starts_with('/') {
        path = path.trim_start_matches('/').to_string();
    }

    let abs = root.join(&path);
    if abs.components().count() == 0 {
        return None;
    }

    Some(path)
}

fn generate_test_file_from_scaffold(
    root: &Path,
    test_file: &str,
    source_file: &str,
) -> Option<String> {
    let source_path = root.join(source_file);
    if !source_path.exists() {
        return None;
    }

    let lang = Path::new(source_file)
        .extension()
        .and_then(|ext| ext.to_str())
        .map(Language::from_extension)
        .unwrap_or(Language::Unknown);

    let config = match lang {
        Language::Rust => crate::test_scaffold::ScaffoldConfig::rust(),
        Language::Php => crate::test_scaffold::ScaffoldConfig::php(),
        _ => return None,
    };

    let scaffolded =
        crate::test_scaffold::scaffold_file(&source_path, root, &config, false).ok()?;

    if scaffolded.test_file != test_file {
        return None;
    }

    if scaffolded.stub_count == 0 || scaffolded.content.trim().is_empty() {
        return None;
    }

    Some(scaffolded.content)
}

pub(super) fn apply_missing_test_file_fixes(
    result: &CodeAuditResult,
    root: &Path,
    new_files: &mut Vec<NewFile>,
) {
    for finding in &result.findings {
        if finding.kind != AuditFinding::MissingTestFile {
            continue;
        }

        let Some(test_file) = extract_expected_test_path(&finding.description) else {
            continue;
        };

        let abs_test_path = root.join(&test_file);
        if abs_test_path.exists() || new_files.iter().any(|new_file| new_file.file == test_file) {
            continue;
        }

        let Some(candidate) = generate_test_file_candidate(root, &test_file, &finding.file) else {
            continue;
        };
        new_files.push(new_file(
            AuditFinding::MissingTestFile,
            FixSafetyTier::SafeWithChecks,
            test_file,
            candidate.content,
            format!("Create missing test file for '{}'", finding.file),
        ));
    }
}

pub(super) fn apply_missing_test_method_fixes(
    result: &CodeAuditResult,
    root: &Path,
    fixes: &mut Vec<Fix>,
    new_files: &mut Vec<NewFile>,
    skipped: &mut Vec<SkippedFile>,
) {
    for finding in &result.findings {
        if finding.kind != AuditFinding::MissingTestMethod {
            continue;
        }

        let Some(expected_test_method) = extract_expected_test_method(&finding.description) else {
            continue;
        };
        let Some(source_method) = extract_source_method_name(&finding.description) else {
            continue;
        };

        let test_file_opt = extract_test_file_from_missing_test_method(&finding.description)
            .or_else(|| derive_expected_test_file_path(root, &finding.file));

        if test_file_opt.is_none() {
            let source_language = detect_language(Path::new(&finding.file));
            if is_inline_test_language(&source_language) {
                let source_abs = root.join(&finding.file);
                let source_content = std::fs::read_to_string(&source_abs).unwrap_or_default();

                if source_content.contains(&expected_test_method) {
                    continue;
                }

                if source_content.contains("#[cfg(test)]") {
                    let test_stub = generate_test_method_stub(
                        &source_language,
                        &expected_test_method,
                        &finding.file,
                        &source_method,
                    );

                    fixes.push(Fix {
                        file: finding.file.clone(),
                        required_methods: vec![],
                        required_registrations: vec![],
                        insertions: vec![insertion(
                            InsertionKind::MethodStub,
                            AuditFinding::MissingTestMethod,
                            test_stub,
                            format!(
                                "Scaffold missing test method '{}' for '{}::{}' (inline)",
                                expected_test_method, finding.file, source_method
                            ),
                        )],
                        applied: false,
                    });
                    continue;
                }
            }

            skipped.push(SkippedFile {
                file: finding.file.clone(),
                reason: format!(
                    "Could not derive test file path for missing test method '{}'",
                    expected_test_method
                ),
            });
            continue;
        }

        let test_file = test_file_opt.unwrap();
        let ext = Path::new(&test_file)
            .extension()
            .and_then(|ext| ext.to_str())
            .map(Language::from_extension)
            .unwrap_or(Language::Unknown);

        if test_method_exists_in_file(root, &test_file, &expected_test_method, new_files) {
            continue;
        }

        let test_stub =
            generate_test_method_stub(&ext, &expected_test_method, &finding.file, &source_method);

        let file_exists = root.join(&test_file).exists();
        if file_exists {
            fixes.push(Fix {
                file: test_file,
                required_methods: vec![],
                required_registrations: vec![],
                insertions: vec![insertion(
                    InsertionKind::MethodStub,
                    AuditFinding::MissingTestMethod,
                    test_stub,
                    format!(
                        "Scaffold missing test method '{}' for '{}::{}'",
                        expected_test_method, finding.file, source_method
                    ),
                )],
                applied: false,
            });
        } else if let Some(existing) = new_files
            .iter_mut()
            .find(|new_file| new_file.file == test_file)
        {
            if !existing.content.contains(&expected_test_method) {
                existing.content.push('\n');
                existing.content.push_str(&test_stub);
            }
        } else {
            let Some(mut candidate) = generate_test_file_candidate(root, &test_file, &finding.file)
            else {
                continue;
            };
            candidate.content.push('\n');
            candidate.content.push_str(&test_stub);
            new_files.push(new_file(
                AuditFinding::MissingTestFile,
                FixSafetyTier::SafeWithChecks,
                test_file,
                candidate.content,
                format!("Create missing test file for '{}'", finding.file),
            ));
        }
    }
}
