use crate::code_audit::conventions::Language;
use crate::code_audit::{fixer, AuditFinding, CodeAuditResult};
use regex::Regex;
use std::collections::HashSet;
use std::path::Path;

pub fn generate_audit_fixes(result: &CodeAuditResult, root: &Path) -> fixer::FixResult {
    fixer::generate_fixes_impl(result, root)
}

pub(crate) fn extract_expected_test_path(description: &str) -> Option<String> {
    let needle = "expected '";
    let start = description.find(needle)? + needle.len();
    let rest = &description[start..];
    let end = rest.find('\'')?;
    Some(rest[..end].to_string())
}

pub(crate) fn extract_expected_test_method(description: &str) -> Option<String> {
    let needle = "expected '";
    let start = description.find(needle)? + needle.len();
    let rest = &description[start..];
    let end = rest.find('\'')?;
    Some(rest[..end].to_string())
}

pub(crate) fn extract_test_file_from_missing_test_method(description: &str) -> Option<String> {
    let needle = " in '";
    let start = description.find(needle)? + needle.len();
    let rest = &description[start..];
    let end = rest.find('\'')?;
    Some(rest[..end].to_string())
}

pub(crate) fn extract_source_method_name(description: &str) -> Option<String> {
    let needle = "Method '";
    let start = description.find(needle)? + needle.len();
    let rest = &description[start..];
    let end = rest.find('\'')?;
    Some(rest[..end].to_string())
}

pub(crate) fn generate_test_method_stub(
    language: &Language,
    expected_test_method: &str,
    source_file: &str,
    source_method: &str,
) -> String {
    match language {
        Language::Rust => format!(
            "#[test]\n#[ignore = \"autogenerated scaffold\"]\nfn {}() {{\n    todo!(\"Autogenerated scaffold for {}::{}\");\n}}\n",
            expected_test_method, source_file, source_method
        ),
        Language::Php => format!(
            "public function {}(): void {{\n    $this->markTestIncomplete('Autogenerated scaffold for {}::{}');\n}}\n",
            expected_test_method, source_file, source_method
        ),
        _ => format!(
            "// Add {} for {}::{}\n",
            expected_test_method, source_file, source_method
        ),
    }
}

pub(crate) fn generate_method_stub(sig: &fixer::MethodSignature) -> String {
    let body = stub_body(&sig.name, &sig.language);
    match sig.language {
        Language::Php => format!("\n    {} {{\n{}\n    }}\n", sig.signature, body),
        Language::Rust => format!("\n    {} {{\n{}\n    }}\n", sig.signature, body),
        Language::JavaScript | Language::TypeScript => {
            format!("\n    {} {{\n{}\n    }}\n", sig.signature, body)
        }
        Language::Unknown => String::new(),
    }
}

fn stub_body(method_name: &str, language: &Language) -> String {
    match language {
        Language::Php => {
            format!(
                "        throw new \\RuntimeException('Not implemented: {}');",
                method_name
            )
        }
        Language::Rust => format!("        todo!(\"{}\")", method_name),
        Language::JavaScript | Language::TypeScript => {
            format!("        throw new Error('Not implemented: {}');", method_name)
        }
        Language::Unknown => String::new(),
    }
}

pub(crate) fn generate_import_statement(import_path: &str, language: &Language) -> String {
    match language {
        Language::Rust => format!("use {};", import_path),
        Language::Php => format!("use {};", import_path),
        Language::JavaScript | Language::TypeScript => {
            let name = import_path
                .rsplit("::")
                .next()
                .or_else(|| import_path.rsplit('/').next())
                .unwrap_or(import_path);
            format!("import {{ {} }} from '{}';", name, import_path)
        }
        Language::Unknown => format!("use {};", import_path),
    }
}

pub(crate) fn generate_namespace_declaration(
    namespace: &str,
    language: &Language,
) -> Option<String> {
    match language {
        Language::Php => Some(format!("namespace {};", namespace)),
        _ => None,
    }
}

pub(crate) fn generate_type_conformance_declaration(
    type_name: &str,
    conformance: &str,
    language: &Language,
) -> String {
    match language {
        Language::Rust => format!("\nimpl {} for {} {{\n}}\n", conformance, type_name),
        Language::Php | Language::TypeScript => conformance.to_string(),
        Language::JavaScript | Language::Unknown => conformance.to_string(),
    }
}

pub(crate) fn generate_registration_stub(hook_name: &str) -> String {
    let callback = hook_name
        .strip_prefix("wp_")
        .or_else(|| hook_name.strip_prefix("datamachine_"))
        .unwrap_or(hook_name);

    format!(
        "        add_action('{}', [$this, '{}']);",
        hook_name, callback
    )
}

pub(crate) fn merge_fixes_per_file(fixes: Vec<fixer::Fix>) -> Vec<fixer::Fix> {
    let mut map: std::collections::HashMap<String, fixer::Fix> = std::collections::HashMap::new();
    let mut order: Vec<String> = Vec::new();

    for fix in fixes {
        if let Some(existing) = map.get_mut(&fix.file) {
            for method in fix.required_methods {
                if !existing.required_methods.contains(&method) {
                    existing.required_methods.push(method);
                }
            }
            for registration in fix.required_registrations {
                if !existing.required_registrations.contains(&registration) {
                    existing.required_registrations.push(registration);
                }
            }
            existing.insertions.extend(fix.insertions);
        } else {
            order.push(fix.file.clone());
            map.insert(fix.file.clone(), fix);
        }
    }

    order.into_iter().filter_map(|f| map.remove(&f)).collect()
}

pub(crate) fn generate_test_file_stub(test_file: &str, source_file: &str) -> String {
    let ext = Path::new(test_file)
        .extension()
        .and_then(|e| e.to_str())
        .map(Language::from_extension)
        .unwrap_or(Language::Unknown);

    match ext {
        Language::Rust => {
            let name = Path::new(source_file)
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("module")
                .replace('-', "_");
            format!(
                "// Auto-generated by `homeboy audit --fix`\n// Source: {}\n\n#[test]\n#[ignore = \"autogenerated scaffold\"]\nfn test_{}_placeholder() {{\n    todo!(\"Autogenerated scaffold - replace with real assertions\");\n}}\n",
                source_file, name
            )
        }
        Language::Php => {
            format!(
                "<?php\n\n// Auto-generated by `homeboy audit --fix`\n// Source: {}\n\nuse PHPUnit\\Framework\\TestCase;\n\nfinal class GeneratedPlaceholderTest extends TestCase {{\n    public function test_placeholder(): void {{\n        $this->markTestIncomplete('Autogenerated scaffold - replace with real assertions');\n    }}\n}}\n",
                source_file
            )
        }
        _ => format!(
            "// Auto-generated by `homeboy audit --fix`\n// Source: {}\n// Add tests\n",
            source_file
        ),
    }
}

pub(crate) struct TestFileCandidate {
    pub content: String,
}

pub(crate) fn generate_test_file_candidate(
    root: &Path,
    test_file: &str,
    source_file: &str,
) -> Option<TestFileCandidate> {
    if let Some(scaffolded) = generate_test_file_from_scaffold(root, test_file, source_file) {
        return Some(TestFileCandidate {
            content: scaffolded,
        });
    }

    Some(TestFileCandidate {
        content: generate_test_file_stub(test_file, source_file),
    })
}

fn extract_source_file_from_comment(content: &str) -> Option<String> {
    content.lines().find_map(|line| {
        line.trim()
            .strip_prefix("// Source: ")
            .or_else(|| line.trim().strip_prefix("* Source: "))
            .or_else(|| line.trim().strip_prefix("// Source: "))
            .map(|value| value.trim().to_string())
    })
}

pub(crate) fn mapping_from_source_comment(content: &str) -> Option<(String, String)> {
    let source_file = extract_source_file_from_comment(content)?;
    let expected_test_path = derive_expected_test_file_path(Path::new("."), &source_file)
        .or_else(|| fallback_expected_test_path(&source_file))?;

    Some((source_file, expected_test_path))
}

fn fallback_expected_test_path(source_file: &str) -> Option<String> {
    let source_path = Path::new(source_file);
    let ext = source_path.extension()?.to_str()?;
    let name = source_path.file_stem()?.to_str()?;
    let dir = source_path
        .parent()
        .and_then(|parent| parent.strip_prefix("src").ok())
        .map(|parent| parent.to_string_lossy().trim_start_matches('/').to_string())
        .unwrap_or_default();

    Some(if dir.is_empty() {
        format!("tests/{}_test.{}", name, ext)
    } else {
        format!("tests/{}/{}_test.{}", dir, name, ext)
    })
}

pub(crate) fn extract_source_file_from_test_stub(description: &str) -> Option<String> {
    let marker = " for '";
    let start = description.find(marker)? + marker.len();
    let rest = &description[start..];
    let end = rest.find("::")?;
    Some(rest[..end].to_string())
}

pub(crate) fn extract_expected_test_method_from_fix_description(
    description: &str,
) -> Option<String> {
    let marker = "Scaffold missing test method '";
    let start = description.find(marker)? + marker.len();
    let rest = &description[start..];
    let end = rest.find('"').or_else(|| rest.find('\''))?;
    Some(rest[..end].to_string())
}

pub(crate) fn test_method_exists_in_file(
    root: &Path,
    test_file: &str,
    expected_test_method: &str,
    new_files: &[fixer::NewFile],
) -> bool {
    if let Some(new_file) = new_files.iter().find(|new_file| new_file.file == test_file) {
        return new_file.content.contains(&expected_test_method);
    }

    let abs_path = root.join(test_file);
    match std::fs::read_to_string(&abs_path) {
        Ok(content) => content.contains(expected_test_method),
        Err(_) => false,
    }
}

pub(crate) fn derive_expected_test_file_path(root: &Path, source_file: &str) -> Option<String> {
    let ext = Path::new(source_file).extension()?.to_str()?;
    let manifest = crate::extension::find_extension_for_file_ext(ext, "audit")?;
    let mapping = manifest.test_mapping()?;

    let mut path = crate::code_audit::test_mapping::source_to_test_path(source_file, mapping)?;
    if path.starts_with('/') {
        path = path.trim_start_matches('/').to_string();
    }

    let abs = root.join(&path);
    if abs.components().count() == 0 {
        return None;
    }

    Some(path)
}

fn generate_test_file_from_scaffold(
    root: &Path,
    test_file: &str,
    source_file: &str,
) -> Option<String> {
    let source_path = root.join(source_file);
    if !source_path.exists() {
        return None;
    }

    let lang = Path::new(source_file)
        .extension()
        .and_then(|e| e.to_str())
        .map(Language::from_extension)
        .unwrap_or(Language::Unknown);

    let config = match lang {
        Language::Rust => crate::test_scaffold::ScaffoldConfig::rust(),
        Language::Php => crate::test_scaffold::ScaffoldConfig::php(),
        _ => return None,
    };

    let scaffolded =
        crate::test_scaffold::scaffold_file(&source_path, root, &config, false).ok()?;

    if scaffolded.test_file != test_file {
        return None;
    }

    if scaffolded.stub_count == 0 || scaffolded.content.trim().is_empty() {
        return None;
    }

    Some(scaffolded.content)
}

pub(crate) fn extract_suggested_path(suggestion: &str) -> Option<String> {
    let needle = "Replace with `";
    let start = suggestion.find(needle)? + needle.len();
    let rest = &suggestion[start..];
    let end = rest.find('`')?;
    Some(rest[..end].to_string())
}

pub(crate) fn should_remove_broken_doc_line(line: &str, dead_path: &str) -> bool {
    let trimmed = line.trim();
    let bullet_like = trimmed.starts_with('-') || trimmed.starts_with('*');
    bullet_like && trimmed.contains(dead_path)
}

pub(crate) fn is_actionable_comment_finding(kind: &AuditFinding) -> bool {
    matches!(kind, AuditFinding::TodoMarker | AuditFinding::LegacyComment)
}

pub(crate) fn extract_function_name_from_unreferenced(description: &str) -> Option<String> {
    let needle = "Public function '";
    let start = description.find(needle)? + needle.len();
    let rest = &description[start..];
    let end = rest.find('\'')?;
    Some(rest[..end].to_string())
}

pub(crate) fn module_path_from_file(file_path: &str) -> String {
    crate::core::symbol_graph::module_path_from_file(file_path)
}

fn normalize_item_name(name: &str) -> String {
    name.trim().to_string()
}

pub(crate) fn find_parsed_item_by_name<'a>(
    items: &'a [crate::extension::ParsedItem],
    requested_name: &str,
) -> Option<&'a crate::extension::ParsedItem> {
    if let Some(exact) = items.iter().find(|item| item.name == requested_name) {
        return Some(exact);
    }

    let requested = normalize_item_name(requested_name);
    let mut normalized_matches = items
        .iter()
        .filter(|item| normalize_item_name(&item.name) == requested);

    let first = normalized_matches.next()?;
    if normalized_matches.next().is_some() {
        return None;
    }

    Some(first)
}

pub(crate) fn parse_items_for_dedup(
    file_ext: &str,
    content: &str,
    file_path: &str,
) -> Option<Vec<crate::extension::ParsedItem>> {
    if let Some(grammar) = crate::code_audit::core_fingerprint::load_grammar_for_ext(file_ext) {
        let items = crate::utils::grammar_items::parse_items(content, &grammar);
        if !items.is_empty() {
            return Some(
                items
                    .into_iter()
                    .map(crate::extension::ParsedItem::from)
                    .collect(),
            );
        }
    }

    let manifest = crate::extension::find_extension_for_file_ext(file_ext, "refactor")?;
    let parse_cmd = serde_json::json!({
        "command": "parse_items",
        "file_path": file_path,
        "content": content,
        "items": [],
    });

    crate::extension::run_refactor_script(&manifest, &parse_cmd)
        .and_then(|v| v.get("items").cloned())
        .and_then(|v| serde_json::from_value(v).ok())
}

pub(crate) fn extract_signatures_from_items(
    content: &str,
    language: &Language,
) -> Vec<fixer::MethodSignature> {
    let file_ext = match language {
        Language::Php => "php",
        Language::Rust => "rs",
        Language::JavaScript => "js",
        Language::TypeScript => "ts",
        Language::Unknown => return Vec::new(),
    };

    let Some(grammar) = crate::code_audit::core_fingerprint::load_grammar_for_ext(file_ext) else {
        return Vec::new();
    };

    let symbols = crate::utils::grammar::extract(content, &grammar);
    let lines: Vec<&str> = content.lines().collect();

    symbols
        .into_iter()
        .filter(|symbol| matches!(symbol.concept.as_str(), "function" | "free_function" | "method"))
        .filter_map(|symbol| {
            let name = symbol.name()?.to_string();
            let line_idx = symbol.line.checked_sub(1)?;
            let signature = lines
                .get(line_idx)
                .map(|line| line.trim().to_string())
                .filter(|line| !line.is_empty())
                .unwrap_or_else(|| name.clone());

            Some(fixer::MethodSignature {
                name,
                signature,
                language: language.clone(),
            })
        })
        .collect()
}

fn insertion(
    kind: fixer::InsertionKind,
    finding: AuditFinding,
    code: String,
    description: String,
) -> fixer::Insertion {
    fixer::Insertion {
        safety_tier: kind.safety_tier(),
        kind,
        finding,
        auto_apply: false,
        blocked_reason: None,
        preflight: None,
        code,
        description,
    }
}

fn new_file(
    finding: AuditFinding,
    safety_tier: fixer::FixSafetyTier,
    file: String,
    content: String,
    description: String,
) -> fixer::NewFile {
    fixer::NewFile {
        file,
        finding,
        safety_tier,
        auto_apply: false,
        blocked_reason: None,
        preflight: None,
        content,
        description,
        written: false,
    }
}

pub(crate) fn generate_unreferenced_export_fixes(
    result: &CodeAuditResult,
    root: &Path,
    fixes: &mut Vec<fixer::Fix>,
    skipped: &mut Vec<fixer::SkippedFile>,
) {
    for finding in &result.findings {
        if finding.kind != AuditFinding::UnreferencedExport {
            continue;
        }

        let Some(fn_name) = extract_function_name_from_unreferenced(&finding.description) else {
            continue;
        };

        let abs_path = root.join(&finding.file);
        let language = fixer::detect_language(&abs_path);
        if !matches!(language, Language::Rust) {
            continue;
        }

        let content = match std::fs::read_to_string(&abs_path) {
            Ok(content) => content,
            Err(_) => continue,
        };

        if content.contains(&format!("pub(crate) fn {}", fn_name))
            || content.contains(&format!("pub(super) fn {}", fn_name))
        {
            continue;
        }

        if is_reexported(&finding.file, &fn_name, root) {
            skipped.push(fixer::SkippedFile {
                file: finding.file.clone(),
                reason: format!(
                    "Function '{}' is re-exported or used by binary crate — cannot narrow visibility",
                    fn_name
                ),
            });
            continue;
        }

        let target_patterns = [
            format!("pub fn {}(", fn_name),
            format!("pub fn {}<", fn_name),
            format!("pub async fn {}(", fn_name),
            format!("pub async fn {}<", fn_name),
        ];

        let found_line = content.lines().enumerate().find_map(|(index, line)| {
            let trimmed = line.trim();
            target_patterns
                .iter()
                .any(|pat| trimmed.contains(pat.as_str()))
                .then_some(index + 1)
        });

        let Some(line_num) = found_line else {
            skipped.push(fixer::SkippedFile {
                file: finding.file.clone(),
                reason: format!("Could not locate `pub fn {}` declaration in file", fn_name),
            });
            continue;
        };

        let line_content = content.lines().nth(line_num - 1).unwrap_or("");
        let (from, to) = if line_content.contains(&format!("pub async fn {}", fn_name)) {
            (
                "pub async fn".to_string(),
                "pub(crate) async fn".to_string(),
            )
        } else {
            ("pub fn".to_string(), "pub(crate) fn".to_string())
        };

        fixes.push(fixer::Fix {
            file: finding.file.clone(),
            required_methods: vec![],
            required_registrations: vec![],
            insertions: vec![insertion(
                fixer::InsertionKind::VisibilityChange {
                    line: line_num,
                    from: from.clone(),
                    to: to.clone(),
                },
                AuditFinding::UnreferencedExport,
                format!("{} → {}", from, to),
                format!(
                    "Narrow visibility of '{}': {} → {} (unreferenced export)",
                    fn_name, from, to
                ),
            )],
            applied: false,
        });
    }
}

pub(crate) fn generate_duplicate_function_fixes(
    result: &CodeAuditResult,
    root: &Path,
    fixes: &mut Vec<fixer::Fix>,
    new_files: &mut Vec<fixer::NewFile>,
    skipped: &mut Vec<fixer::SkippedFile>,
) {
    const MIN_EXTRACT_GROUP_SIZE: usize = 4;
    const SKIP_EXTRACT_NAMES: &[&str] = &[
        "__construct",
        "constructor",
        "new",
        "set_up",
        "setUp",
        "tear_down",
        "tearDown",
    ];

    for group in &result.duplicate_groups {
        let group_size = 1 + group.remove_from.len();

        if SKIP_EXTRACT_NAMES.contains(&group.function_name.as_str()) {
            continue;
        }

        if group_size < MIN_EXTRACT_GROUP_SIZE {
            generate_simple_duplicate_fixes(group, root, fixes, skipped);
            continue;
        }

        let canonical_abs = root.join(&group.canonical_file);
        let ext = canonical_abs
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("");
        let language = fixer::detect_language(&canonical_abs);
        let use_extract_shared = matches!(language, Language::Php)
            && !crate::code_audit::is_test_path(&group.canonical_file);

        let canonical_content = match std::fs::read_to_string(&canonical_abs) {
            Ok(content) => content,
            Err(_) => {
                skipped.push(fixer::SkippedFile {
                    file: group.canonical_file.clone(),
                    reason: format!(
                        "Cannot read canonical file for duplicate `{}`",
                        group.function_name
                    ),
                });
                continue;
            }
        };

        let manifest = if use_extract_shared {
            crate::extension::find_extension_for_file_ext(ext, "refactor")
        } else {
            None
        };

        let Some(manifest) = manifest else {
            generate_simple_duplicate_fixes(group, root, fixes, skipped);
            continue;
        };

        let mut file_entries = Vec::new();
        let mut any_read_failure = false;
        for remove_file in &group.remove_from {
            let abs_path = root.join(remove_file);
            match std::fs::read_to_string(&abs_path) {
                Ok(content) => {
                    file_entries.push(serde_json::json!({
                        "path": remove_file,
                        "content": content,
                    }));
                }
                Err(_) => {
                    skipped.push(fixer::SkippedFile {
                        file: remove_file.clone(),
                        reason: format!(
                            "Cannot read file to remove duplicate `{}`",
                            group.function_name
                        ),
                    });
                    any_read_failure = true;
                }
            }
        }
        if any_read_failure && file_entries.is_empty() {
            continue;
        }

        let mut all_paths: Vec<&str> = vec![group.canonical_file.as_str()];
        all_paths.extend(group.remove_from.iter().map(|path| path.as_str()));

        let extract_cmd = serde_json::json!({
            "command": "extract_shared",
            "function_name": group.function_name,
            "canonical_file": group.canonical_file,
            "canonical_content": canonical_content,
            "files": file_entries,
            "all_file_paths": all_paths,
        });

        let Some(result_val) = crate::extension::run_refactor_script(&manifest, &extract_cmd)
        else {
            generate_simple_duplicate_fixes(group, root, fixes, skipped);
            continue;
        };

        if result_val.get("error").is_some() {
            let err = result_val["error"].as_str().unwrap_or("unknown error");
            skipped.push(fixer::SkippedFile {
                file: group.canonical_file.clone(),
                reason: format!(
                    "extract_shared failed for `{}`: {}",
                    group.function_name, err
                ),
            });
            continue;
        }

        if result_val
            .get("skip")
            .and_then(|value| value.as_bool())
            .unwrap_or(false)
        {
            let reason = result_val
                .get("reason")
                .and_then(|value| value.as_str())
                .unwrap_or("extension decided to skip");
            skipped.push(fixer::SkippedFile {
                file: group.canonical_file.clone(),
                reason: format!("Skipped `{}`: {}", group.function_name, reason),
            });
            continue;
        }

        if let (Some(trait_file), Some(trait_content)) = (
            result_val
                .get("trait_file")
                .and_then(|value| value.as_str()),
            result_val
                .get("trait_content")
                .and_then(|value| value.as_str()),
        ) {
            if !new_files.iter().any(|nf| nf.file == trait_file) {
                let trait_name = result_val
                    .get("trait_name")
                    .and_then(|value| value.as_str())
                    .unwrap_or("SharedTrait");
                new_files.push(new_file(
                    AuditFinding::DuplicateFunction,
                    fixer::FixSafetyTier::PlanOnly,
                    trait_file.to_string(),
                    trait_content.to_string(),
                    format!(
                        "Create trait `{}` for shared `{}` method",
                        trait_name, group.function_name
                    ),
                ));
            }
        }

        if let Some(file_edits) = result_val
            .get("file_edits")
            .and_then(|value| value.as_array())
        {
            for edit in file_edits {
                let Some(file) = edit
                    .get("file")
                    .and_then(|value| value.as_str())
                    .map(str::to_string)
                else {
                    continue;
                };

                let mut insertions = Vec::new();

                if let Some(remove_lines) = edit.get("remove_lines") {
                    if let (Some(start), Some(end)) = (
                        remove_lines
                            .get("start_line")
                            .and_then(|value| value.as_u64()),
                        remove_lines
                            .get("end_line")
                            .and_then(|value| value.as_u64()),
                    ) {
                        insertions.push(insertion(
                            fixer::InsertionKind::FunctionRemoval {
                                start_line: start as usize,
                                end_line: end as usize,
                            },
                            AuditFinding::DuplicateFunction,
                            String::new(),
                            format!(
                                "Remove duplicate `{}` (extracted to shared trait)",
                                group.function_name
                            ),
                        ));
                    }
                }

                if let Some(import) = edit.get("add_import").and_then(|value| value.as_str()) {
                    insertions.push(insertion(
                        fixer::InsertionKind::ImportAdd,
                        AuditFinding::DuplicateFunction,
                        import.to_string(),
                        format!("Import shared trait for `{}`", group.function_name),
                    ));
                }

                if let Some(use_trait) = edit.get("add_use_trait").and_then(|value| value.as_str())
                {
                    insertions.push(insertion(
                        fixer::InsertionKind::TraitUse,
                        AuditFinding::DuplicateFunction,
                        use_trait.to_string(),
                        format!("Use shared trait for `{}`", group.function_name),
                    ));
                }

                if !insertions.is_empty() {
                    fixes.push(fixer::Fix {
                        file,
                        required_methods: vec![],
                        required_registrations: vec![],
                        insertions,
                        applied: false,
                    });
                }
            }
        }
    }
}

fn generate_simple_duplicate_fixes(
    group: &crate::code_audit::DuplicateGroup,
    root: &Path,
    fixes: &mut Vec<fixer::Fix>,
    skipped: &mut Vec<fixer::SkippedFile>,
) {
    for remove_file in &group.remove_from {
        let abs_path = root.join(remove_file.as_str());
        let ext = abs_path
            .extension()
            .and_then(|value| value.to_str())
            .unwrap_or("");

        let content = match std::fs::read_to_string(&abs_path) {
            Ok(content) => content,
            Err(_) => {
                skipped.push(fixer::SkippedFile {
                    file: remove_file.clone(),
                    reason: format!(
                        "Cannot read file to remove duplicate `{}`",
                        group.function_name
                    ),
                });
                continue;
            }
        };

        let items = parse_items_for_dedup(ext, &content, remove_file);
        let Some(items) = items else {
            skipped.push(fixer::SkippedFile {
                file: remove_file.clone(),
                reason: format!(
                    "Cannot locate `{}` boundaries in {} — no grammar or extension available",
                    group.function_name, remove_file
                ),
            });
            continue;
        };

        let Some(item) = find_parsed_item_by_name(&items, &group.function_name) else {
            skipped.push(fixer::SkippedFile {
                file: remove_file.clone(),
                reason: format!(
                    "Function `{}` not found by parser in {}",
                    group.function_name, remove_file
                ),
            });
            continue;
        };

        let import_path = module_path_from_file(&group.canonical_file);
        let import_stmt = match ext {
            "rs" => format!("use crate::{}::{};", import_path, group.function_name),
            _ => format!(
                "import {{ {} }} from '{}';",
                group.function_name, import_path
            ),
        };

        let mut insertions = vec![insertion(
            fixer::InsertionKind::FunctionRemoval {
                start_line: item.start_line,
                end_line: item.end_line,
            },
            AuditFinding::DuplicateFunction,
            String::new(),
            format!(
                "Remove duplicate `{}` (canonical copy in {})",
                group.function_name, group.canonical_file
            ),
        )];

        if !content.contains(&import_stmt) {
            insertions.push(insertion(
                fixer::InsertionKind::ImportAdd,
                AuditFinding::DuplicateFunction,
                import_stmt,
                format!("Import `{}` from canonical location", group.function_name),
            ));
        }

        fixes.push(fixer::Fix {
            file: remove_file.clone(),
            required_methods: vec![],
            required_registrations: vec![],
            insertions,
            applied: false,
        });
    }
}

pub(crate) fn is_reexported(file_path: &str, fn_name: &str, root: &Path) -> bool {
    let source_path = Path::new(file_path);

    let mut current = source_path.parent();
    while let Some(dir) = current {
        for filename in &["mod.rs", "lib.rs"] {
            let check_path = root.join(dir).join(filename);
            if check_path.exists()
                && std::fs::read_to_string(&check_path)
                    .ok()
                    .is_some_and(|content| has_pub_use_of(&content, fn_name))
            {
                return true;
            }
        }
        current = dir.parent();
    }

    is_used_by_binary_crate(fn_name, root)
}

pub(crate) fn has_pub_use_of(content: &str, fn_name: &str) -> bool {
    let mut in_pub_use_block = false;
    for line in content.lines() {
        let trimmed = line.trim();

        if in_pub_use_block {
            if trimmed.contains(fn_name) {
                return true;
            }
            if trimmed.contains("};") || trimmed == "}" {
                in_pub_use_block = false;
            }
        } else if trimmed.starts_with("pub use") {
            if trimmed.contains(fn_name) {
                return true;
            }
            if trimmed.contains('{') && !trimmed.contains('}') {
                in_pub_use_block = true;
            }
        }
    }
    false
}

fn is_used_by_binary_crate(fn_name: &str, root: &Path) -> bool {
    let src = root.join("src");
    let main_rs = src.join("main.rs");
    if main_rs.exists()
        && std::fs::read_to_string(&main_rs)
            .ok()
            .is_some_and(|content| content.contains(fn_name))
    {
        return true;
    }

    let lib_rs = src.join("lib.rs");
    let lib_mods = if lib_rs.exists() {
        std::fs::read_to_string(&lib_rs)
            .ok()
            .map(|content| extract_mod_names(&content))
            .unwrap_or_default()
    } else {
        HashSet::new()
    };

    let main_mods = if main_rs.exists() {
        std::fs::read_to_string(&main_rs)
            .ok()
            .map(|content| extract_mod_names(&content))
            .unwrap_or_default()
    } else {
        HashSet::new()
    };

    for mod_name in main_mods.difference(&lib_mods) {
        let mod_dir = src.join(mod_name);
        if mod_dir.is_dir() && scan_dir_for_reference(&mod_dir, fn_name) {
            return true;
        }

        let mod_file = src.join(format!("{}.rs", mod_name));
        if mod_file.exists()
            && std::fs::read_to_string(&mod_file)
                .ok()
                .is_some_and(|content| content.contains(fn_name))
        {
            return true;
        }
    }

    false
}

fn extract_mod_names(content: &str) -> HashSet<String> {
    let mut mods = HashSet::new();
    let re = Regex::new(r"(?m)^\s*(?:pub\s+)?mod\s+(\w+)\s*;").unwrap();
    for cap in re.captures_iter(content) {
        mods.insert(cap[1].to_string());
    }
    mods
}

fn scan_dir_for_reference(dir: &Path, fn_name: &str) -> bool {
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(_) => return false,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if scan_dir_for_reference(&path, fn_name) {
                return true;
            }
        } else if path.extension().is_some_and(|ext| ext == "rs")
            && std::fs::read_to_string(&path)
                .ok()
                .is_some_and(|content| content.contains(fn_name))
        {
            return true;
        }
    }

    false
}
